hydra:
  run:
    dir: outputs/test/${model.modelname}/${model.ckpt.name}/${run_name}
  job: # automatically go to the job folder (needed for hydra > 1.2 with new behavior)
    chdir: true

# Global configurations shared between different modules
run_name: CURE_noise${data.noise_ratio}

seed: 1234
logger_level: INFO

# Composing nested config with default
defaults:
  - _self_
  - data: webvid-covr_CEL
  - test: webvid-covr_CEL
  - machine: server
  - trainer: gpu
  - model: blip-large-CEL
  - model/ckpt: webvid-covr
  - model/loss: tal
  - model/loss_terms: si_ti
  - trainer/logger: none

  - experiment: null

paths: ${machine.paths}
